# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy requirement files and install dependencies
COPY requirements.txt requirements.txt
COPY .env .env
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Streamlit app into the container
COPY chatbot.py chatbot.py

# Expose the Streamlit default port
EXPOSE 8501

# Command to run the Streamlit app
CMD ["streamlit", "run", "chatbot.py", "--server.port=8501", "--server.address=0.0.0.0"]